name: Build

on:
  push:
    branches:
      - 'main'
      - 'v*'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'main'
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: denoland/setup-deno@v1
      with:
        deno-version: v1.20.x
    - run: mkdir -p dist && cp lthn.json dist/lthn.json && cp index.html dist/index.html
    - name: Get the version
      id: get_version
      if: startsWith(github.ref, 'refs/tags/')
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
    - name: Install zip
      uses: montudor/action-zip@v1
    - name: package
      working-directory: dist/
      run: zip -qq -r ../setup-${{ steps.get_version.outputs.VERSION }}.zip .
    - uses: actions/upload-artifact@v2
      with:
        name: setup-${{ steps.get_version.outputs.VERSION }}
        path: setup-${{ steps.get_version.outputs.VERSION }}.zip
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: setup-${{ steps.get_version.outputs.VERSION }}.zip

