name: Build

on:
  push:
    branches:
      - 'main'
      - 'v*'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'main'
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: montudor/action-zip@v1
      with:
        args: zip -qq -r package.zip  .
    - uses: actions/upload-artifact@v2
      with:
        name: Package
        path: package.zip
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: package.zip

